export {default as MainSection} from './main-section'
export {default as LogosSection} from './logos-section'
export {default as InfoSection} from './info-section'
export {default as FindOutSection} from './find-out-section'
export {default as ReviewSection} from './review-section'
